name: Run Python Script
on: [push]
jobs:
  runs-python-script:
    runs-on: ubuntu-latest
    steps:
        - name: Inicio
          run: echo "Comienza Action"
        - name: Clona Repo
          uses: actions/checkout@v6
        - name: muestra archivos
          run: ls -al
        - name: Ejecuta Scripts
          run: python app-py
